alter table usuarios add column if not exists email text unique;
alter table usuarios add column if not exists auth_user_id uuid references auth.users(id);
create table if not exists despesas (id bigserial primary key, descricao text, categoria text, valor numeric, data date, observacoes text);
create table if not exists receitas (id bigserial primary key, descricao text, categoria text, valor numeric, data date, forma_pagamento text, observacoes text);
create table if not exists contas (id bigserial primary key, descricao text, categoria text, valor numeric, vencimento date, status text default 'pendente', tipo text default 'pagar', observacoes text);
create table if not exists orcamento_pessoal (id bigserial primary key, descricao text, categoria text, valor numeric, tipo text default 'despesa', mes text, data date, data_pagamento date, status text default 'previsto', observacoes text, recorrente boolean default false, prazo_recorrencia integer, recorrencia_origem_id bigint, forma_pagamento text);
alter table clientes add column if not exists bloqueado boolean default false;
alter table veiculos add column if not exists venc_ipva date;
alter table veiculos add column if not exists venc_seguro date;
alter table reservas add column if not exists veiculo_id bigint references veiculos(id);
alter table reservas add column if not exists cliente_id bigint references clientes(id);
alter table reservas add column if not exists contrato_id bigint references contratos(id);
create index if not exists idx_reservas_veiculo on reservas(veiculo_id);
alter table veiculos add column if not exists km_atual integer;
alter table veiculos add column if not exists km_revisao_proxima integer;
alter table veiculos add column if not exists seguradora text;
alter table veiculos add column if not exists apolice text;
alter table veiculos add column if not exists seguro_franquia numeric;
alter table veiculos add column if not exists rastreador boolean default false;
alter table veiculos add column if not exists rastreador_fornecedor text;
alter table veiculos add column if not exists rastreador_mensalidade numeric;
alter table veiculos add column if not exists pneus_km_troca integer;
alter table veiculos add column if not exists pneus_vida_util_km integer default 40000;
alter table contratos add column if not exists combustivel_saida text;
alter table contratos add column if not exists combustivel_retorno text;
alter table contratos add column if not exists combustivel_cobranca numeric;
create table if not exists fornecedores (id bigserial primary key, nome text not null, tipo text default 'oficina', cnpj text, telefone text, email text, endereco text, observacoes text, ativo boolean default true);
alter table manutencao add column if not exists fornecedor_id bigint references fornecedores(id);
create index if not exists idx_manutencao_fornecedor on manutencao(fornecedor_id);
create table if not exists sinistros (id bigserial primary key, veiculo_id bigint references veiculos(id), contrato_id bigint references contratos(id), cliente_id bigint references clientes(id), data date, tipo text, descricao text, valor_prejuizo numeric, valor_franquia numeric, status text default 'aberto', numero_sinistro text, terceiro_envolvido text, boletim_ocorrencia text, observacoes text);
create index if not exists idx_sinistros_veiculo on sinistros(veiculo_id);
alter table contratos add column if not exists km_franquia numeric;
alter table contratos add column if not exists forma_pagamento text;
alter table contratos add column if not exists previsao_pagamento date;
alter table contratos add column if not exists status_pagamento text default 'pendente';
alter table despesas add column if not exists status text default 'previsto';
alter table despesas add column if not exists data_pagamento date;
alter table despesas add column if not exists recorrente boolean default false;
alter table despesas add column if not exists prazo_recorrencia integer;
alter table despesas add column if not exists recorrencia_origem_id bigint;
alter table despesas add column if not exists manutencao_id bigint;
alter table receitas add column if not exists status text default 'previsto';
alter table receitas add column if not exists data_pagamento date;
alter table receitas add column if not exists recorrente boolean default false;
alter table receitas add column if not exists prazo_recorrencia integer;
alter table manutencao add column if not exists status_financeiro text default 'pendente';
alter table manutencao add column if not exists data_pagamento date;
alter table manutencao add column if not exists data_previsao_pagamento date;
alter table multas add column if not exists vencimento date;
alter table multas add column if not exists data_pagamento date;
alter table multas add column if not exists cobrado_cliente text default 'nao';
alter table multas add column if not exists valor_cobrado numeric;
create table if not exists audit_log (id bigserial primary key, tabela text, operacao text, registro_id text, dados jsonb, criado_em timestamptz default now());
create table if not exists ocupacao_historico (id bigserial primary key, dia date unique, total int, alugados int, disponiveis int, manutencao int, taxa numeric);